import { DomainConfig } from "@/lib/types";

const snapshotSkillFields = [
  { id: "observedDate", label: "Observed/Assessed Date", type: "date" as const },
  {
    id: "followUpPlan",
    label: "Follow-Up Learning Plan",
    type: "textarea" as const,
    placeholder: "What is the next step for instruction or support?",
  },
];

const reassessmentFields = [
  {
    id: "score",
    label: "Score",
    type: "score" as const,
    helpText: "Use the common assessment scale of 0, 1, or 2.",
  },
  { id: "reassessmentDate", label: "Reassessment Date", type: "date" as const },
  {
    id: "reassessmentScore",
    label: "Reassessment Score",
    type: "score" as const,
  },
  {
    id: "notes",
    label: "Notes",
    type: "textarea" as const,
    placeholder: "Observations, prompts used, or instructional notes",
  },
];

export const domainConfigs: DomainConfig[] = [
  {
    id: "language-literacy",
    title: "Language/Literacy",
    shortDescription: "Snapshot items for oral language, phonological awareness, letter knowledge, print knowledge, and writing.",
    skills: [
      {
        id: "understanding-and-using-new-words",
        title: "Understanding and using new words",
        groupTitle: "Oral language",
        groupNote: "begins Week 2",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-and-remembering-key-information-in-a-book",
        title: "Understanding and remembering key information in a book",
        groupTitle: "Oral language",
        groupNote: "begins Week 2",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-how-to-draw-inferences-from-book-information",
        title: "Understanding how to draw inferences from book information",
        groupTitle: "Oral language",
        groupNote: "begins Week 2",
        fields: snapshotSkillFields,
      },
      {
        id: "identifying-sounds",
        title: "Identifying sounds",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "recognizing-naming-and-suggesting-words-that-rhyme",
        title: "Recognizing, naming, and suggesting words that rhyme",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "forming-and-segmenting-compound-words",
        title: "Forming and segmenting compound words (assessed week 11)",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "segmenting-words-into-syllables-and-blending-syllables",
        title: "Segmenting words into syllables and blending syllables (assessed week 16)",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "identifying-the-initial-sounds-of-familiar-words",
        title: "Identifying the initial sounds of familiar words (assessed week 23)",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "blending-body-and-coda",
        title: "*Blending the two initial sounds (body) with the ending sounds (coda) of one-syllable word (assessed week 30)",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "blending-onset-and-rime",
        title: "*Blending the initial sound (onset) with the remaining sounds (rime) of one-syllable word (assessed week 30)",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "identifying-final-sound",
        title: "*Identifying final sound",
        groupTitle: "Phonological awareness",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "letter-sounds",
        title: "Letter sounds",
        groupTitle: "Letter knowledge",
        groupNote: "begins Week 6",
        fields: snapshotSkillFields,
      },
      {
        id: "identifying-uppercase-letters",
        title: "Identifying uppercase letters (assessed week 43)",
        groupTitle: "Letter knowledge",
        groupNote: "begins Week 6",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-how-books-work",
        title: "Understanding how books work",
        groupTitle: "Print Knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-how-sentences-work",
        title: "Understanding how sentences work",
        groupTitle: "Print Knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "beginning-skills-in-forming-letters-and-words",
        title: "Beginning skills in forming letters and words",
        groupTitle: "Writing",
        groupNote: "begins Week 7",
        fields: snapshotSkillFields,
      },
    ],
    assessments: [
      {
        id: "week-16-syllables",
        title: "Week 16: Syllables Assessment",
        week: 16,
        description: "Tracks how well the child segments or identifies syllables.",
        fields: [
          ...reassessmentFields,
          { id: "correctResponses", label: "Correct Responses", type: "number" },
        ],
      },
      {
        id: "week-23-initial-sounds",
        title: "Week 23: Initial Sounds",
        week: 23,
        description: "Records initial sound identification performance.",
        fields: [
          ...reassessmentFields,
          { id: "itemsMissed", label: "Items Missed", type: "text", placeholder: "Optional list of missed items" },
        ],
      },
      {
        id: "week-30-sound-blending",
        title: "Week 30: Sound Blending",
        week: 30,
        description: "Captures blending performance and follow-up notes.",
        fields: reassessmentFields,
      },
      {
        id: "week-43-letter-knowledge",
        title: "Week 43: Letter Knowledge",
        week: 43,
        description: "Supports end-of-year letter knowledge scoring.",
        fields: [
          ...reassessmentFields,
          { id: "uppercaseKnown", label: "Uppercase Letters Known", type: "number" },
          { id: "lowercaseKnown", label: "Lowercase Letters Known", type: "number" },
        ],
      },
    ],
  },
  {
    id: "mathematics",
    title: "Mathematics",
    shortDescription: "Snapshot items for number, geometry, pattern, and measurement knowledge.",
    skills: [
      {
        id: "understanding-small-numbers",
        title: "Understanding small numbers",
        groupTitle: "Number knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-comparison-words-used-with-number-quantities",
        title: "Understanding comparison words used with number quantities",
        groupTitle: "Number knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "one-to-one-counting",
        title: "One-to-one counting (assessed week 13)",
        groupTitle: "Number knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-that-the-last-number-counted-indicates-how-many",
        title: "Understanding that the last number counted indicates \"how many\" (assessed week 13)",
        groupTitle: "Number knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "recognizing-and-naming-numerals",
        title: "Recognizing and naming numerals (assessed week 22)",
        groupTitle: "Number knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-the-concept-of-one-more",
        title: "Understanding the concept of \"one more\" (assessed week 27)",
        groupTitle: "Number knowledge",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "recognizing-and-labeling-basic-shapes",
        title: "Recognizing and labeling basic shapes",
        groupTitle: "Geometric and spatial knowledge",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "creating-basic-shapes",
        title: "Creating basic shapes",
        groupTitle: "Geometric and spatial knowledge",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "recognizing-how-shapes-are-related-to-each-other",
        title: "Recognizing how shapes are related to each other",
        groupTitle: "Geometric and spatial knowledge",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "recognizing-variations-of-basic-shapes",
        title: "Recognizing variations of basic shapes",
        groupTitle: "Geometric and spatial knowledge",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "identifying-basic-patterns",
        title: "Identifying basic patterns",
        groupTitle: "Pattern knowledge",
        groupNote: "begins Week 14",
        fields: snapshotSkillFields,
      },
      {
        id: "creating-basic-patterns",
        title: "Creating basic patterns",
        groupTitle: "Pattern knowledge",
        groupNote: "begins Week 14",
        fields: snapshotSkillFields,
      },
      {
        id: "creating-more-complex-patterns",
        title: "Creating more complex patterns",
        groupTitle: "Pattern knowledge",
        groupNote: "begins Week 14",
        fields: snapshotSkillFields,
      },
      {
        id: "assigning-number-values-when-measuring",
        title: "Assigning number values when measuring",
        groupTitle: "Measurement knowledge",
        groupNote: "begins Week 24",
        fields: snapshotSkillFields,
      },
      {
        id: "using-basic-measurement-skills",
        title: "Using basic measurement skills",
        groupTitle: "Measurement knowledge",
        groupNote: "begins Week 24",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-and-using-standard-forms-of-measurement",
        title: "*Understanding and using standard forms of measurement",
        groupTitle: "Measurement knowledge",
        groupNote: "begins Week 24",
        fields: snapshotSkillFields,
      },
    ],
    assessments: [
      {
        id: "week-13-counting-cardinality",
        title: "Week 13: One-to-One Counting and Cardinality",
        week: 13,
        description: "Captures quantity counting performance and reassessment.",
        fields: [
          ...reassessmentFields,
          { id: "highestCount", label: "Highest Count Demonstrated", type: "number" },
        ],
      },
      {
        id: "week-22-written-numerals",
        title: "Week 22: Written Numerals",
        week: 22,
        description: "Records written numeral recognition or production results.",
        fields: [
          ...reassessmentFields,
          { id: "numeralsCorrect", label: "Numerals Correct", type: "number" },
        ],
      },
      {
        id: "week-27-one-more",
        title: "Week 27: One More",
        week: 27,
        description: "Tracks whether the child can identify one more than a set.",
        fields: reassessmentFields,
      },
    ],
  },
  {
    id: "self-regulation",
    title: "Self-Regulation",
    shortDescription: "Snapshot items for self-control, concentration, and executive function.",
    skills: [
      {
        id: "self-control-of-behaviors",
        title: "Self-control of behaviors",
        groupTitle: "Self-control",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "self-control-of-emotions",
        title: "Self-control of emotions",
        groupTitle: "Self-control",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "self-control-of-thoughts",
        title: "Self-control of thoughts",
        groupTitle: "Self-control",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "concentrating-on-an-experience",
        title: "Concentrating on an experience",
        groupTitle: "Concentration",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "concentrating-on-self",
        title: "Concentrating on self",
        groupTitle: "Concentration",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "concentrating-on-others",
        title: "Concentrating on others",
        groupTitle: "Concentration",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "paying-attention-and-flexibly-shifting-focus",
        title: "Paying attention and flexibly shifting focus",
        groupTitle: "Executive function",
        groupNote: "begins Week 8",
        fields: snapshotSkillFields,
      },
      {
        id: "holding-onto-and-using-information",
        title: "Holding onto and using information",
        groupTitle: "Executive function",
        groupNote: "begins Week 8",
        fields: snapshotSkillFields,
      },
      {
        id: "inhibiting-thoughts-and-responses-inappropriate-to-situation",
        title: "Inhibiting thoughts and responses inappropriate to situation",
        groupTitle: "Executive function",
        groupNote: "begins Week 8",
        fields: snapshotSkillFields,
      },
    ],
  },
  {
    id: "social-emotional",
    title: "Social-Emotional",
    shortDescription: "Snapshot items for relationships, emotion knowledge, perspective-taking, and responsibility.",
    skills: [
      {
        id: "initiating-play",
        title: "Initiating Play",
        groupTitle: "Relationship skills",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "sharing-taking-turns-and-cooperating-with-peers-or-adults",
        title: "Sharing, taking turns, and cooperating with peers or adults",
        groupTitle: "Relationship skills",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "solving-social-problems",
        title: "Solving social problems",
        groupTitle: "Relationship skills",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "being-friendly-and-helpful",
        title: "Being friendly and helpful",
        groupTitle: "Relationship skills",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-different-emotions",
        title: "Understanding different emotions",
        groupTitle: "Emotion knowledge",
        groupNote: "begins Week 10",
        fields: snapshotSkillFields,
      },
      {
        id: "managing-emotions",
        title: "Managing emotions",
        groupTitle: "Emotion knowledge",
        groupNote: "begins Week 10",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-another-persons-perspective",
        title: "Understanding another person's perspective",
        groupTitle: "Perspective-taking",
        groupNote: "begins Week 28",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-and-taking-personal-responsibility",
        title: "Understanding and taking personal responsibility",
        groupTitle: "Personal responsibility",
        groupNote: "begins Week 32",
        fields: snapshotSkillFields,
      },
    ],
  },
  {
    id: "social-studies",
    title: "Social Studies",
    shortDescription: "Snapshot items for diversity, environments, and concepts of time.",
    skills: [
      {
        id: "understanding-some-of-the-ways-individuals-are-unique",
        title: "Understanding some of the ways individuals are unique",
        groupTitle: "Appreciation of individual and family diversity",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-some-of-the-ways-families-are-unique",
        title: "Understanding some of the ways families are unique",
        groupTitle: "Appreciation of individual and family diversity",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "characteristics-of-physical-environments",
        title: "Characteristics of physical environments",
        groupTitle: "Knowledge of social/physical environments",
        groupNote: "begins Week 10",
        fields: snapshotSkillFields,
      },
      {
        id: "characteristics-of-social-environments",
        title: "Characteristics of social environments",
        groupTitle: "Knowledge of social/physical environments",
        groupNote: "begins Week 10",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-yesterday-today-tomorrow-morning-afternoon",
        title: "Understanding yesterday, today, tomorrow, morning, afternoon",
        groupTitle: "Concepts of time",
        groupNote: "begins Week 31",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-how-families-lived-long-ago",
        title: "Understanding how families lived long ago",
        groupTitle: "Concepts of time",
        groupNote: "begins Week 31",
        fields: snapshotSkillFields,
      },
    ],
  },
  {
    id: "creative-expression",
    title: "Creative Expression",
    shortDescription: "Snapshot items for understanding and creating across art, dance, music, and drama.",
    skills: [
      {
        id: "understanding-how-an-artist-creates-art",
        title: "Understanding how an artist creates art",
        groupTitle: "Appreciation and knowledge of creative expression",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-basic-dance-concepts",
        title: "Understanding basic dance concepts",
        groupTitle: "Appreciation and knowledge of creative expression",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-music-concepts",
        title: "Understanding music concepts",
        groupTitle: "Appreciation and knowledge of creative expression",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-drama-concepts",
        title: "Understanding drama concepts",
        groupTitle: "Appreciation and knowledge of creative expression",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "creating-ones-own-artwork",
        title: "Creating one's own artwork",
        groupTitle: "Skills that support creative expression",
        groupNote: "begins Week 5",
        fields: snapshotSkillFields,
      },
      {
        id: "exploring-basic-dance-movements",
        title: "Exploring basic dance movements",
        groupTitle: "Skills that support creative expression",
        groupNote: "begins Week 5",
        fields: snapshotSkillFields,
      },
      {
        id: "creating-music",
        title: "Creating music",
        groupTitle: "Skills that support creative expression",
        groupNote: "begins Week 5",
        fields: snapshotSkillFields,
      },
      {
        id: "creating-drama",
        title: "Creating drama",
        groupTitle: "Skills that support creative expression",
        groupNote: "begins Week 5",
        fields: snapshotSkillFields,
      },
    ],
  },
  {
    id: "science",
    title: "Science",
    shortDescription: "Snapshot items for inquiry and understanding science topics across the year.",
    skills: [
      {
        id: "using-inquiry-skills",
        title: "Using inquiry skills",
        groupTitle: "Inquiry skills",
        groupNote: "begins Week 3",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-basic-characteristics-of-living-and-nonliving-things",
        title: "Understanding basic characteristics of: living and nonliving things (begins Week 12)",
        groupTitle: "Understanding basic characteristics of",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-basic-characteristics-of-life-cycles",
        title: "Understanding basic characteristics of: life cycles (begins Week 19)",
        groupTitle: "Understanding basic characteristics of",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-basic-characteristics-of-habitats",
        title: "Understanding basic characteristics of: habitats (begins Week 26)",
        groupTitle: "Understanding basic characteristics of",
        fields: snapshotSkillFields,
      },
      {
        id: "understanding-basic-characteristics-of-earth-and-space",
        title: "Understanding basic characteristics of: earth and space (begins Week 37)",
        groupTitle: "Understanding basic characteristics of",
        fields: snapshotSkillFields,
      },
    ],
  },
  {
    id: "physical-health",
    title: "Physical/Health",
    shortDescription: "Snapshot items for motor development and good health practices.",
    skills: [
      {
        id: "gross-motor",
        title: "Gross motor",
        groupTitle: "Motor Development",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "fine-motor",
        title: "Fine motor",
        groupTitle: "Motor Development",
        groupNote: "begins Week 4",
        fields: snapshotSkillFields,
      },
      {
        id: "knowledge-of-safety-rules-routines-and-emergency-procedures",
        title: "Knowledge of safety rules, routines, and emergency procedures",
        groupTitle: "Good health practices",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
      {
        id: "knowledge-of-how-to-take-good-physical-care-of-self",
        title: "Knowledge of how to take good physical care of self",
        groupTitle: "Good health practices",
        groupNote: "begins Week 1",
        fields: snapshotSkillFields,
      },
    ],
  },
];

export const domainConfigMap = Object.fromEntries(domainConfigs.map((domain) => [domain.id, domain]));
