import { DomainConfig } from "@/lib/types";

const infantToddlerSkillFields = [
  { id: "observationDate1", label: "Observation Date 1", type: "date" as const },
  { id: "observationDate2", label: "Observation Date 2", type: "date" as const },
  {
    id: "observationNote1",
    label: "Observation Note 1",
    type: "textarea" as const,
    placeholder: "Enter the first observation note",
  },
  {
    id: "observationNote2",
    label: "Observation Note 2",
    type: "textarea" as const,
    placeholder: "Enter the second observation note",
  },
  {
    id: "followUpPlan",
    label: "Follow-Up Learning Plan",
    type: "textarea" as const,
    placeholder: "What is the next step for instruction or support?",
  },
  {
    id: "observationScore1",
    label: "Observation Score 1",
    type: "score" as const,
  },
  {
    id: "observationScore2",
    label: "Observation Score 2",
    type: "score" as const,
  },
  {
    id: "observationScore3",
    label: "Observation Score 3",
    type: "score" as const,
  },
];

export const infantToddlerDomainConfigs: DomainConfig[] = [
  {
    id: "it-communication-language",
    title: "Communication/Language",
    shortDescription: "Infant/toddler Snapshot items for receptive language, expressive language, sounds, print, and pictures.",
    skills: [
      {
        id: "it-birth-12-responds-to-adults-words",
        title: "Birth-12 months: Responds to an adult's words",
        groupTitle: "Receptive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-aware-of-meaning-several-words",
        title: "Birth-12 months: Aware of the meaning of several words",
        groupTitle: "Receptive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-aware-name-familiar-objects-persons-animals",
        title: "12-36 months: Shows awareness of the name of some familiar objects, persons, or animals",
        groupTitle: "Receptive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-aware-simple-action-descriptions",
        title: "12-36 months: Shows awareness of the meaning of some simple action descriptions",
        groupTitle: "Receptive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-coos-babbles-cries",
        title: "Birth-12 months: Uses coos, babbles, cries to communicate with caregiver",
        groupTitle: "Expressive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-uses-words-name-describe",
        title: "12-36 months: Uses a word(s) to name or describe an object, person, animal, or action",
        groupTitle: "Expressive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-uses-words-request-communicate",
        title: "12-36 months: Uses a word(s) to make a request or communicate a need, want, interest, or idea",
        groupTitle: "Expressive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-24-36-uses-different-types-words",
        title: "24-36 months: Uses two or more different types of words",
        groupTitle: "Expressive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-24-36-uses-2-3-words",
        title: "24-36 months: Uses 2-3 words in same utterance",
        groupTitle: "Expressive language",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-interest-different-sounds",
        title: "Birth-12 months: Shows interest in different kinds of sounds",
        groupTitle: "Awareness of differences in sounds",
        groupNote: "begins Block 3 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-imitates-sound",
        title: "Birth-12 months: Imitates a sound made by caregiver or peer",
        groupTitle: "Awareness of differences in sounds",
        groupNote: "begins Block 3 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-imitates-identifies-sound",
        title: "12-36 months: Imitates or identifies a sound made by a caregiver or object",
        groupTitle: "Awareness of differences in sounds",
        groupNote: "begins Block 3 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-24-36-book-picture-text",
        title: "24-36 months: Looks at details in a book picture and notices text with caregiver guidance",
        groupTitle: "Awareness of print and picture",
        groupNote: "begins Block 3",
        fields: infantToddlerSkillFields,
      },
    ],
  },
  {
    id: "it-cognitive",
    title: "Cognitive",
    shortDescription: "Infant/toddler Snapshot items for object inquiry and problem-solving.",
    skills: [
      {
        id: "it-birth-12-senses-explore-objects",
        title: "Birth-12 months: Uses one or more senses to explore an object(s)",
        groupTitle: "Object inquiry",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-simple-action-object",
        title: "Birth-12 months: Uses a simple action to make something happen with an object(s)",
        groupTitle: "Object inquiry",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-24-object-characteristics",
        title: "12-24 months: Uses one or more senses to explore an object's characteristic(s)",
        groupTitle: "Object inquiry",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-object-use-play",
        title: "12-36 months: Explores how an object(s) might be used in play",
        groupTitle: "Object inquiry",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-spatial-awareness",
        title: "12-36 months: Shows a sign(s) of spatial awareness",
        groupTitle: "Object inquiry",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-selects-toy",
        title: "Birth-12 months: Selects a toy to play with from several options",
        groupTitle: "Problem-solving",
        groupNote: "begins Block 3 for Birth-12 months; begins Block 2 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-object-permanence",
        title: "Birth-12 months: Shows a sign(s) of object permanence (awareness that an object exists when it cannot be seen or heard)",
        groupTitle: "Problem-solving",
        groupNote: "begins Block 3 for Birth-12 months; begins Block 2 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-connect-objects",
        title: "12-36 months: Takes apart and puts together objects that connect",
        groupTitle: "Problem-solving",
        groupNote: "begins Block 3 for Birth-12 months; begins Block 2 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-24-36-sorts-matches",
        title: "24-36 months: Sorts and matches objects",
        groupTitle: "Problem-solving",
        groupNote: "begins Block 3 for Birth-12 months; begins Block 2 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
    ],
  },
  {
    id: "it-self-regulation",
    title: "Self-Regulation",
    shortDescription: "Infant/toddler Snapshot items for self-control, concentration, and executive function.",
    skills: [
      {
        id: "it-birth-12-calming-with-support",
        title: "Birth-12 months: Shows a sign(s) of calming down with caregiver support",
        groupTitle: "Self-control",
        groupNote: "begins Block 2",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-calming-with-support",
        title: "12-36 months: Shows a sign(s) of calming down with caregiver support",
        groupTitle: "Self-control",
        groupNote: "begins Block 2",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-attention-object-person-activity",
        title: "Birth-12 months: Pays attention to an object, person, or activity emphasized by a caregiver",
        groupTitle: "Concentration",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-attention-caregiver-requests",
        title: "12-36 months: Pays attention to caregiver requests",
        groupTitle: "Concentration",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-attention-same-different",
        title: "12-36 months: Pays attention to how objects or pictures are the same or different",
        groupTitle: "Concentration",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-persistent-focus",
        title: "Birth-12 months: Shows a sign(s) of persistent focus in watching, securing, or manipulating an object",
        groupTitle: "Executive function",
        groupNote: "begins Block 6 for Birth-12 months; begins Block 3 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-shifts-focus-requested",
        title: "12-36 months: Shifts focus as requested during an activity",
        groupTitle: "Executive function",
        groupNote: "begins Block 6 for Birth-12 months; begins Block 3 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-remembers-object-location",
        title: "12-36 months: Focuses on an object and remembers its location",
        groupTitle: "Executive function",
        groupNote: "begins Block 6 for Birth-12 months; begins Block 3 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
    ],
  },
  {
    id: "it-social-emotional",
    title: "Social-Emotional",
    shortDescription: "Infant/toddler Snapshot items for social interaction and awareness of emotions.",
    skills: [
      {
        id: "it-birth-12-initiates-responds-caregiver",
        title: "Birth-12 months: Initiates and/or responds to communication with a trusted caregiver",
        groupTitle: "Social interaction skills",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-back-and-forth-caregiver",
        title: "Birth-12 months: Participates in back-and-forth exchanges with a trusted caregiver",
        groupTitle: "Social interaction skills",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-back-and-forth-caregiver",
        title: "12-36 months: Participates in back-and-forth interactions with a trusted caregiver",
        groupTitle: "Social interaction skills",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-interest-peers",
        title: "12-36 months: Shows interest in peers",
        groupTitle: "Social interaction skills",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-cooperative-actions-peers",
        title: "12-36 months: Engages in cooperative action(s) with a peer(s)",
        groupTitle: "Social interaction skills",
        groupNote: "begins Block 1",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-facial-expression-feeling",
        title: "12-36 months: Looks at and/or imitates a facial expression typically associated with a particular feeling",
        groupTitle: "Awareness of emotions",
        groupNote: "begins Block 14 for 12-24 months; begins Block 16 for 24-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-happy-sad-feelings",
        title: "12-36 months: Shows awareness of happy and sad feelings",
        groupTitle: "Awareness of emotions",
        groupNote: "begins Block 14 for 12-24 months; begins Block 16 for 24-36 months",
        fields: infantToddlerSkillFields,
      },
    ],
  },
  {
    id: "it-physical-health",
    title: "Physical/Health",
    shortDescription: "Infant/toddler Snapshot items for gross and fine motor development.",
    skills: [
      {
        id: "it-birth-12-rolling-over",
        title: "Birth-12 months: Rolling over",
        groupTitle: "Gross motor development",
        groupNote: "begins Block 1 for Birth-12 months; begins Block 2 for 12-24 months; begins Block 1 for 24-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-lifting-tummy",
        title: "Birth-12 months: Lifting up while on tummy",
        groupTitle: "Gross motor development",
        groupNote: "begins Block 1 for Birth-12 months; begins Block 2 for 12-24 months; begins Block 1 for 24-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-creeping-crawling-sitting-standing-walking",
        title: "Birth-12 months: Engaging in creeping, crawling, sitting, standing, or walking",
        groupTitle: "Gross motor development",
        groupNote: "begins Block 1 for Birth-12 months; begins Block 2 for 12-24 months; begins Block 1 for 24-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-balance-moving-body",
        title: "12-36 months: Maintains balance while moving body or part of body",
        groupTitle: "Gross motor development",
        groupNote: "begins Block 1 for Birth-12 months; begins Block 2 for 12-24 months; begins Block 1 for 24-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-coordinates-body-object",
        title: "12-36 months: Coordinates body movements while manipulating an object",
        groupTitle: "Gross motor development",
        groupNote: "begins Block 1 for Birth-12 months; begins Block 2 for 12-24 months; begins Block 1 for 24-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-reaching",
        title: "Birth-12 months: Reaching",
        groupTitle: "Fine motor development",
        groupNote: "begins Block 2 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-grasping",
        title: "Birth-12 months: Grasping",
        groupTitle: "Fine motor development",
        groupNote: "begins Block 2 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-birth-12-manipulating",
        title: "Birth-12 months: Manipulating",
        groupTitle: "Fine motor development",
        groupNote: "begins Block 2 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-moves-fingers-hands",
        title: "12-36 months: Purposefully moves fingers and/or hands",
        groupTitle: "Fine motor development",
        groupNote: "begins Block 2 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
      {
        id: "it-12-36-hold-manipulate-object",
        title: "12-36 months: Uses fingers and/or hand(s) to hold and/or manipulate an object(s)",
        groupTitle: "Fine motor development",
        groupNote: "begins Block 2 for Birth-12 months; begins Block 1 for 12-36 months",
        fields: infantToddlerSkillFields,
      },
    ],
  },
];

export const infantToddlerDomainConfigMap = Object.fromEntries(
  infantToddlerDomainConfigs.map((domain) => [domain.id, domain]),
);
